version: 3

tasks:
  default:
    cmds:
      - task: "{{.TARGET_TASK}}"
    vars:
      TARGET_TASK:
        sh: gum choose run-app build build-with-app

  build-with-app:
    cmds:
      - go build -v -tags=app ./...

  build:
    cmds:
      - go build -v ./...

  run-app:
    cmds:
      - go run --tags=app ./main.go app
